version: "3.7"

# environment
x-volumes: &env-volume
  ALLOWED_HOSTS: "http://localhost:8080,http://localhost"
  SECRET_KEY: "askrrt23fui4y5t9frhnijqwehry2fg349roimhewdirfjhw3784ryt"

  REDIS_LOCAL_URL: "redis://redis:6379/1"


services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nayan32biswas/docker_downtime:latest
    container_name: docker_downtime_server
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    environment:
      <<: *env-volume
    volumes:
      - ./:/app/server/
    depends_on:
      - redis
    networks:
      - docker_downtime-backend-tier

  redis:
    image: redis:6
    container_name: docker_downtime_redis
    restart: unless-stopped
    networks:
      - docker_downtime-backend-tier
    volumes:
      - docker_downtime-redis:/data

volumes:
  docker_downtime-redis:
    driver: local

networks:
  docker_downtime-backend-tier:
    driver: bridge
